/**
 * Type definitions for detection rules
 */

import type { TaintPath, TaintSource, SecuritySink } from '../types/taint';
import type { ParsedWorkflow } from '../analysis/workflowParser';
import type { WorkflowGraph } from '../types/graph';

/**
 * Finding category - groups related vulnerability types
 */
export type FindingCategory =
	| 'injection'
	| 'ssrf'
	| 'credential-exposure'
	| 'prompt-injection'
	| 'configuration'
	| 'information-disclosure';

/**
 * Severity level for findings
 */
export type FindingSeverity = 'critical' | 'high' | 'medium' | 'low' | 'info';

/**
 * Confidence level for findings
 */
export type FindingConfidence = 'high' | 'medium' | 'low';

/**
 * Security references (CWE, OWASP, etc.)
 */
export interface SecurityReferences {
	/** CWE identifier (e.g., 'CWE-94') */
	cwe?: string;
	/** OWASP category (e.g., 'A03:2021-Injection') */
	owasp?: string;
	/** CAPEC identifier (e.g., 'CAPEC-242') */
	capec?: string;
	/** Link to documentation */
	documentation?: string;
}

/**
 * Remediation guidance for a finding
 */
export interface RemediationGuidance {
	/** Short summary of how to fix */
	summary: string;
	/** Step-by-step remediation steps */
	steps: string[];
	/** Example of a safe pattern (code snippet) */
	safePattern?: string;
	/** Short description of the safe pattern */
	exampleCode?: string;
}

/**
 * Source node information in a finding
 */
export interface FindingSource {
	/** Node name */
	node: string;
	/** Node type (e.g., 'n8n-nodes-base.webhook') */
	nodeType: string;
	/** Field that carries tainted data */
	field: string;
}

/**
 * Sink node information in a finding
 */
export interface FindingSink {
	/** Node name */
	node: string;
	/** Node type (e.g., 'n8n-nodes-base.code') */
	nodeType: string;
	/** Parameter that receives tainted data */
	parameter: string;
	/** The dangerous expression/pattern if detected */
	dangerousExpression?: string;
}

/**
 * A security finding generated by a detection rule
 */
export interface Finding {
	/** Unique finding ID (e.g., 'RV-RCE-001-1706012345678') */
	id: string;
	/** ID of the rule that generated this finding */
	ruleId: string;
	/** Severity of the finding */
	severity: FindingSeverity;
	/** Confidence level */
	confidence: FindingConfidence;
	/** Short title describing the vulnerability */
	title: string;
	/** Detailed description of the vulnerability */
	description: string;
	/** Category of the vulnerability */
	category: FindingCategory;
	/** Source node information */
	source: FindingSource;
	/** Sink node information */
	sink: FindingSink;
	/** Path of nodes from source to sink */
	path: string[];
	/** Remediation guidance */
	remediation: RemediationGuidance;
	/** Security references (CWE, OWASP) */
	references: SecurityReferences;
	/** Additional metadata */
	metadata: Record<string, unknown>;
}

/**
 * Rule metadata for documentation and filtering
 */
export interface RuleMetadata {
	/** Unique rule identifier (e.g., 'RV-RCE-001') */
	id: string;
	/** Human-readable rule name */
	name: string;
	/** Description of what the rule detects */
	description: string;
	/** Category of vulnerabilities this rule detects */
	category: FindingCategory;
	/** Default severity for findings from this rule */
	severity: FindingSeverity;
	/** Tags for filtering and categorization */
	tags: string[];
	/** Security references */
	references: SecurityReferences;
}

/**
 * Context provided to rules during detection
 */
export interface RuleContext {
	/** Parsed workflow */
	workflow: ParsedWorkflow;
	/** Workflow graph */
	graph: WorkflowGraph;
	/** Detected taint sources */
	sources: TaintSource[];
	/** Detected security sinks */
	sinks: SecuritySink[];
	/** Detected taint paths (source to sink flows) */
	taintPaths: TaintPath[];
}

/**
 * Base interface for all detection rules
 */
export interface DetectionRule {
	/** Rule metadata */
	metadata: RuleMetadata;

	/**
	 * Check if this rule is applicable to the workflow
	 * (e.g., only run SQL injection rule if SQL nodes exist)
	 */
	isApplicable(context: RuleContext): boolean;

	/**
	 * Run detection and return findings
	 */
	detect(context: RuleContext): Finding[];
}

/**
 * Configuration for a single rule
 */
export interface RuleConfig {
	/** Whether the rule is enabled */
	enabled: boolean;
	/** Override the default severity */
	severityOverride?: FindingSeverity;
	/** Custom patterns for this rule (rule-specific) */
	customPatterns?: string[];
}

/**
 * Configuration for all rules
 */
export type RulesConfig = Record<string, RuleConfig>;

/**
 * Options for running rules
 */
export interface RunRulesOptions {
	/** Rule configuration overrides */
	config?: RulesConfig;
	/** Only run rules with these IDs */
	ruleIds?: string[];
	/** Only run rules in these categories */
	categories?: FindingCategory[];
	/** Minimum severity to include in results */
	minSeverity?: FindingSeverity;
}

/**
 * Result of running all rules
 */
export interface RulesResult {
	/** All findings from all rules */
	findings: Finding[];
	/** Number of rules that were run */
	rulesRun: number;
	/** Number of rules that were skipped */
	rulesSkipped: number;
	/** Any errors that occurred during rule execution */
	errors: RuleError[];
	/** Duration in milliseconds */
	duration: number;
}

/**
 * Error that occurred during rule execution
 */
export interface RuleError {
	/** Rule ID that failed */
	ruleId: string;
	/** Error message */
	message: string;
	/** Stack trace if available */
	stack?: string;
}

/**
 * Utility type for creating findings
 */
export interface FindingBuilder {
	/** Create a finding from a taint path */
	fromTaintPath(
		taintPath: TaintPath,
		options: {
			ruleId: string;
			title: string;
			description: string;
			category: FindingCategory;
			confidence: FindingConfidence;
			remediation: RemediationGuidance;
			references: SecurityReferences;
			metadata?: Record<string, unknown>;
		},
	): Finding;
}

/**
 * Helper function to create unique finding IDs
 */
export function createFindingId(ruleId: string): string {
	return `${ruleId}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

/**
 * Helper function to determine effective severity based on sanitization
 */
export function getEffectiveSeverity(
	baseSeverity: FindingSeverity,
	isSanitized: boolean,
): FindingSeverity {
	if (!isSanitized) {
		return baseSeverity;
	}

	// Reduce severity by one level if sanitized
	const severityOrder: FindingSeverity[] = ['critical', 'high', 'medium', 'low', 'info'];
	const currentIndex = severityOrder.indexOf(baseSeverity);
	const newIndex = Math.min(currentIndex + 1, severityOrder.length - 1);
	return severityOrder[newIndex];
}

/**
 * Severity comparison helper
 */
export const SEVERITY_ORDER: Record<FindingSeverity, number> = {
	critical: 0,
	high: 1,
	medium: 2,
	low: 3,
	info: 4,
};

/**
 * Compare two severities
 * Returns negative if a is more severe, positive if b is more severe, 0 if equal
 */
export function compareSeverity(a: FindingSeverity, b: FindingSeverity): number {
	return SEVERITY_ORDER[a] - SEVERITY_ORDER[b];
}

/**
 * Check if severity meets minimum threshold
 */
export function meetsSeverityThreshold(
	severity: FindingSeverity,
	minSeverity: FindingSeverity,
): boolean {
	return SEVERITY_ORDER[severity] <= SEVERITY_ORDER[minSeverity];
}
